/*
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/
library euler.problem45;

final List<int> tNumbers = List<int>.generate(100000, (i) => i * (i + 1) ~/ 2);
final List<int> pNumbers =
    List<int>.generate(100000, (i) => i * (3 * i - 1) ~/ 2);
final List<int> hNumbers = List<int>.generate(100000, (i) => i * (2 * i - 1));

void main() {
  for (int i = 286; i < tNumbers.length; i++) {
    if (pNumbers.contains(tNumbers[i]) && hNumbers.contains(tNumbers[i])) {
      print(tNumbers[i]);
      break;
    }
  }
}
