/*
Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/
library euler.problem44;

final List<int> numbers =
    List<int>.generate(10000, (i) => i * (3 * i - 1) ~/ 2);

void main() {
  numbers.removeAt(0);
  for (int i = 1; i < numbers.length; i++) {
    for (int j = 0; j < i; j++) {
      if (numbers.contains(numbers[i] + numbers[j]) &&
          numbers.contains(numbers[i] - numbers[j])) {
        print(numbers[i] - numbers[j]);
      }
    }
  }
}
